services:
  django-app:
    image: ghcr.io/${GH_REPOSITORY}/django-app:${CI_IMAGE_TAG}
    build:
      context: ./app
      dockerfile: Dockerfile
      target: prod
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: ghcr.io/${GH_REPOSITORY}/db:${CI_IMAGE_TAG}
    container_name: ${MYSQL_HOSTNAME}
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env
  nginx:
    image: ghcr.io/${GH_REPOSITORY}/nginx:${CI_IMAGE_TAG}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_data:/home/app/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - django-app

volumes:
  mysql_data:
  static_data:
